ungrouped:
  hosts:
    ec2: 
      ansible_port: 22
      ansible_host: 35.180.12.251
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ./secrets/cesi-devops-2304-key.pem
      ansible_become: true