name: 'Terraform deploy'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Secret to File
      # You may pin to the exact commit or the version.
      # uses: MobileDevOps/secret-to-file-action@be5f14e82c235ccde011f6ab0f6c984b35dc34c6
      uses: MobileDevOps/secret-to-file-action@v1.0.0
      with:
        # Base64 encoded content for the file
        base64-encoded-secret: ${{ secrets.TERRAFORM_SECRETS }}
        # Name of the file for the content
        filename: secrets.auto.tfvars
        # Folder path for the created file
        working-directory: ./8.aws-ec2
          

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      working-directory: ./8.aws-ec2
      run: terraform init

    # Checks that all Terraform configuration files adhere to a canonical format
    # - name: Terraform Format
    #   working-directory: ./8.aws-ec2
    #   run: terraform fmt -check

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      working-directory: ./8.aws-ec2
      run: terraform plan -input=false

      # On push to "main", build or change infrastructure according to Terraform configuration files
      # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
    - name: Terraform Apply
      working-directory: ./8.aws-ec2
      run: terraform apply -auto-approve -input=false

    - name: Terraform Ouputs
      working-directory: ./8.aws-ec2
      run: terraform output instance_public_ip

    - name: Terraform Inventory
      working-directory: ./8.aws-ec2
      run: terraform output -raw instance_public_ip | awk '{ print "all:\n  hosts:\n    webserver:\n      ansible_host: " $1 "\n      ansible_user: ubuntu\n      ansible_become: true\n      ansible_ssh_private_key_file: ./secrets/my-key.pem" }' > ./ansible/my-inventory.yml

    - name: Secret SSH to File
      # You may pin to the exact commit or the version.
      # uses: MobileDevOps/secret-to-file-action@be5f14e82c235ccde011f6ab0f6c984b35dc34c6
      uses: MobileDevOps/secret-to-file-action@v1.0.0
      with:
        # Base64 encoded content for the file
        base64-encoded-secret: ${{ secrets.SSH_PEM }}
        # Name of the file for the content
        filename: my-key.pem
        # is-executable: true
        # Folder path for the created file
        working-directory: ./8.aws-ec2/ansible/secrets

    - name: Ansible
      # You may pin to the exact commit or the version.
      # uses: alex-oleshkevich/setup-ansible@f879ce3cf11a7315e130919a797526b0c6bfd272
      uses: alex-oleshkevich/setup-ansible@v1.0.1
      # with:
      #   # The version of Ansible to install.
      #   version: 
      working-directory: ./8.aws-ec2/ansible
      run: ANSIBLE_HOST_KEY_CHECKING=false ansible-playbook -i my-inventory.yml playbook.yaml
    
    - name: Terraform Destroy
      working-directory: ./8.aws-ec2
      run: terraform destroy -auto-approve -input=false
